<!DOCTYPE SolarSystem [
<!ELEMENT SolarSystem (planet, planet, planet, planet, planet, planet, planet, planet, planet)>
<!ELEMENT planet (name,orbit,rotation,moon,speed,rings,size)>
<!ELEMENT moon (orbit, number,speed,size)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT orbit (#PCDATA)>
<!ELEMENT rotation (#PCDATA)>
<!ELEMENT speed (#PCDATA)>
<!ELEMENT rings (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT number (#PCDATA)>
]>
<SolarSystem>
	<planet>
		<name>mercury.obj</name>
		<orbit>0</orbit>
		<rotation></rotation>
		<moon>
			<orbit></orbit>
			<number></number>
			<speed></speed>
			<size></size>
		</moon>
		<speed></speed>
		<rings></rings>
		<size></size>	
	</planet> 

	<planet>
		<name>venus.obj</name>
		<orbit>1</orbit>
		<rotation></rotation>
		<moon>
		<orbit></orbit>
				<number></number>
				<speed></speed>
				<size></size>
		</moon>
		<speed></speed>
		<rings></rings>
		<size></size>	
	</planet> 

	<planet>
		<name>earth.obj</name>
		<orbit>2</orbit>
		<rotation></rotation>
		<moon>
		<orbit></orbit>
				<number></number>
				<speed></speed>
				<size></size>
		</moon>
		<speed></speed>
		<rings></rings>
		<size></size>	
	</planet> 

	<planet>
		<name>mars.obj</name>
		<orbit>3</orbit>
		<rotation></rotation>
		<moon>
		<orbit></orbit>
				<number></number>
				<speed></speed>
				<size></size>
		</moon>
		<speed></speed>
		<rings></rings>
		<size></size>	
	</planet> 

	<planet>
		<name>jupiter.obj</name>
		<orbit>4</orbit>
		<rotation></rotation>
		<moon>
		<orbit></orbit>
				<number></number>
				<speed></speed>
				<size></size>
		</moon>
		<speed></speed>
		<rings></rings>
		<size></size>	
	</planet> 
	<planet>
		<name>saturn.obj</name>
		<orbit>5</orbit>
		<rotation></rotation>
		<moon>
		<orbit></orbit>
				<number></number>
				<speed></speed>
				<size></size>
		</moon>
		<speed></speed>
		<rings></rings>
		<size></size>	
	</planet> 
	<planet>
		<name>uranus.obj</name>
		<orbit>6</orbit>
		<rotation></rotation>
		<moon>
			<orbit></orbit>
			<number></number>
			<speed></speed>
			<size></size>
		</moon>
		<speed></speed>
		<rings></rings>
		<size></size>	
	</planet> 
	<planet>
		<name>neptune.obj</name>
		<orbit>7</orbit>
		<rotation></rotation>
		<moon>
			<orbit></orbit>
			<number></number>
			<speed></speed>
			<size></size>
		</moon>
		<speed></speed>
		<rings></rings>
		<size></size>	
	</planet> 
	<planet>
		<name>pluto.obj</name>
		<orbit>8</orbit>
		<rotation></rotation>
		<moon>
			<orbit></orbit>
			<number></number>
			<speed></speed>
			<size></size>
		</moon>
		<speed></speed>
		<rings></rings>
		<size></size>	
	</planet> 
</SolarSystem>